import Head from 'next/head';
import Home from '../components/Home';
import { creationData } from '../data/creationData';
import styles from '../styles/HomePage.module.css';

export default function HomePage({ creationListData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />

    </div>
  );
}

export async function getStaticProps() {
  const data = creationData;

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: { creationListData: data }, // will be passed to the page component as props
  };
}
